### PR TITLE
Basic documentation setup

### PR DESCRIPTION
**Pull request by karllark**
This gets the basic documentation setup.  Ready for more material and this should be done contemporaneous with updates to the code.  Partially address #1.

1) Basic documentation laid out.  Some fixes to code docstrings to enable them to parse correctly.  Documentation needs to be expanded, but this should get us started.

2) Moved modelpacks to pahfit/packs and renamed them to clearly be science packs (no instrument info).  Needed as all package files need to be in the pahfit subdirectory for packaging (e.g., pip installable package).

3) Other minor updates to get things running.

### CODE REVIEW

**Comment by karllark** [comment]
Not a very exciting PR, but it should get the docs in better shape.  Can merge w/o a review given this, but would be good to get a 2nd set of eyes if at all possible.

**Comment by alexmaragko** [comment]
Looks good. What was the issue with the docstrings?

**Comment by jdtsmith** [comment]
Looks good on a quick read through.

**Comment by karllark** [comment]
Thanks for the quick review!  Much appreciated.

Was a couple of not recognized sections and I had created bad plotting in the Drude1D docstring.  All fixed now.  :-)  I'll go ahead and merge - at least then it will create the better formatted pages on readthedocs.

**Pull request merged**
