### PR TITLE
small changes to docs

### PR DESCRIPTION
**Pull request by els1**
Added "intrinsic" or "unattenuated" to amplitudes of BB and features (issue 130)

Added comment that we use astropy Gaussian1D and Drude1D + link (issue 122)

Added comment stating IDL PAHFIT uses fractional FWHM while here we use FWHM
for Drude profiles (issue 152). We can update this if we decide to change it.

### CODE REVIEW

**Comment by els1** [comment]
I also changed the file pahfit.component_models.BlackBody1D.rst and pahfit.component_models.S07_attenuation.rst (so I can reference them) but git does not say they are changed nor upload them. Not sure why.

**Comment by karllark** [comment]
@els: ready for review?

**Comment by els1** [comment]
@karllark yes

**Review by karllark — APPROVED** [review]
Looks good to me.

**Pull request merged**
