### PR TITLE
Read function (v01)

### PR DESCRIPTION
**Pull request by alexmaragko**
Creation of read function. Currently not called in the main code.

### CODE REVIEW

**Comment by karllark** [comment]
This pull request **introduces 4 alerts** when merging d3ffd8a49d90b0846b770213284ba34dac8cd9f2 into 61efe1bde2a43a52824211aa4333214ee948e232 - [view on LGTM.com](https://lgtm.com/projects/g/PAHFIT/pahfit/rev/pr-70197c36296a806b1ba9568c004fdd40d6431f8d)

**new alerts:**

* 4 for Unused local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by alexmaragko** [comment]
Yes, the 4 created dictionaries need to be called just like the sci_pack in PAHFIT.py. The question is do we want to do it inside the read function or in PAHFIT.py ?

**Comment by karllark** [comment]
Creating those variables inside the read function is good.  But they need to be returned by the read function to be able to be used later.  A simple return as a tuple of the variables would work for now at least.

**Comment by alexmaragko** [comment]
I have updated the read function to return a tuple with the variables.

**Comment by karllark** [comment]
Great.  I'm going to merge.  We can see how it integrates with the init function as well as how it interacts with what is needed to read the proposed YML file.

**Pull request merged**
