### PR TITLE
JWST pack files

### PR DESCRIPTION
**Pull request by alexmaragko**
JWST science pack files in ipac format, based on JWST simulations of the Orion's Bar ionization front (see https://pdrs4all.org/publications/ for details).

- JWST_pack_file.ipac coveres lines and dust features between 0.7 and 27.8 microns. Features in the overlap wavelengths between NIRspec and MIRI-MRS are those measured in the MIRI wavelenths.
- JWST_pack_file_NIRspec.ipac covers lines and dust features between 0.7 and 5.26 microns.
- JWST_pack_file_MIRI-MRS.ipac covers lines and dust features between 4.69 and 27.8 microns.

Emission lines and dust features were fitted with Gaussian1D and Drude1D models/profiles respectively, at separate smaller wavelength regions (not in one go of the entire NIR/MIR simulated spectra.)

- A height/sigma threshold was used for emission line identification. Below are some example of lines identified and fitted, and non-identified lines. Subsequently, the number of lines in the pack files depend on the threshold applied. Refinement of the lines and packs will be done with actual JWST spectra. 

JWST_sims_IF_emission_lines_example
JWST_sims_IF_emission_lines_example_zoom

- Identified lines were then cross-correlated with the species from provided tables, as CLOUDY computed lines in the simulations are in general expected to be more than those resolved in actual observations. 
- Currently, emission lines have the species name only. This will be updated to include a wavelength string, based on the lines central wavelength given in the table.

## Notes on PAHFIT fitting 

- Dummy uncertainties 10% of the flux were used for the fitting.  
- Fitting the entire 0.7 - 27.8 micron spectrum (~22300 wavelength elements!) required ~ 1 hour on a core-i5 without giving a successful fit. Perhaps partial fitting in smaller regions is required.
- Using the entire pack file in smaller/subset wavelength regions is ~ 4x more time consuming compared to when trimming the pack file to the input wavelength range.   

## Example fitting on the 5 - 15 micron region of the simulations. 
- No details because of the single points from the very narrow emission lines.
Table_synthetic_spectrum_IF_MIR_Orion_Bar_R6000_factor_2_SOC_Cloudy_Pellegrini_4-15
- Zooming in.
Table_synthetic_spectrum_IF_MIR_Orion_Bar_R6000_factor_2_SOC_Cloudy_Pellegrini_4-15_zoomed
- Using 4000 fit_maxiter.
Table_synthetic_spectrum_IF_MIR_Orion_Bar_R6000_factor_2_SOC_Cloudy_Pellegrini_4-15_maxiter_4000_zoomed

### CODE REVIEW

**Comment by alexmaragko** [comment]
Here is a brute fit (no redshift correction or proper unit conversion) and comparison between the different packs on the 5-15 micron JWST data of galaxy VV114.
- JWST_pack_file_MIRI-MRS.ipac
VV114_JWST_PAHFIT_5-15_4000_maxiter
- ISO_SWS_pack_file_R_1600.ipac from #215 
VV114_JWST_PAHFIT_5-15_ISOPack_4000_maxiter
- scipack_ExGal_SpitzerIRSSLLL.ipac
VV114_JWST_PAHFIT_5-15_SpitzerPack_4000_maxiter

**Comment by ThomasSYLai** [comment]
We should be able to fit the emission lines by properly shifting the spectrum back to the rest frame.

**Comment by alexmaragko** [comment]
Added new JWST packs based on the PDR dissociation front (DF) simulations.

- Fit to the 5-15 micron region of the DF simulations using the `JWST_PDR_DF_MIRI-MRS_pack_file.ipac` pack file.
JWST_sims_PDR_DF
- Fit to the 5-15 micron JWST data of galaxy VV114 using the `JWST_PDR_DF_MIRI-MRS_pack_file.ipac` pack file.
VV114_JWST_PDR-DF_pack

**Comment by jdtsmith** [comment]
I'm going to close this for now since our pack format has diverged since this was written.  Definitely still interested in improvements and the birth of a `pdr.yaml` science pack.  Probably starting small and building lines in as you go is the right approach.

**Pull request closed without merging**
