### PR TITLE
Initial Spitzer/JWST instrument packs

### PR DESCRIPTION
**Pull request by jdtsmith**
Intended for testing use with PR#222.

### CODE REVIEW

**Comment by jdtsmith** [comment]
Torsten Boeker pointed me to [some lovely FITS files for NIRSPEC resolution](https://jwst-docs.stsci.edu/jwst-near-infrared-spectrograph/nirspec-instrumentation/nirspec-dispersers-and-filters#NIRSpecDispersersandFilters-DispersioncurvesfortheNIRSpecdispersers), which I fitted and included. 

Some other changes:

- `instrument.resolution()` to go with `fwhm`. 
- Use as many polynomial coefficients as needed (`jwst.nirspec.prism` needing A LOT). 
- Remove trailing zero coeffs. 

Just waiting for similar MIRI values (@karllark!).

**Comment by karllark** [comment]
Here is the MIRI info Alvaro Labiano just emailed me.  He says ignore the "etalon" column (ground-test info).

image

image

**Comment by jdtsmith** [comment]
> Here is the MIRI info Alvaro Labiano just emailed me. He says ignore the "etalon" column (ground-test info).

Awesome, thanks.  I'll convert into "plain" a + bx + cx^2 polynomials and stick them in.  Do you happen to have the coverage/range for each segment?

**Comment by karllark** [comment]
See https://jwst-docs.stsci.edu/jwst-mid-infrared-instrument/miri-observing-modes/miri-medium-resolution-spectroscopy

**Comment by jdtsmith** [comment]
Thanks Karl.  I have pushed MIRI data based on these fits, and updated NIRSPEC coverage.  I think this is good to go.  Could you give it a quick sanity check, look over the naming conventions, etc.?  

Testing for a given segment is trivial:

```python
ins='jwst.miri.mrs.3.A'
x=np.linspace(*wave_range(ins))
ax.plot(x,resolution(ins,x))
```

**Comment by jdtsmith** [comment]
Here's the MRS FWHM plot for reference:  [jwst_miri_mrs_fwhm.pdf](https://github.com/PAHFIT/pahfit/files/9173995/jwst_miri_mrs_fwhm.pdf).  Pretty big jumps between 3C and 4A.  

image

**Comment by karllark** [comment]
Can you provide a resolution plot as well?  That is what is provide in the docs - makes for easier comparison.

**Comment by karllark** [comment]
It would be great if we had a documentation page for the different instrument packs that describes them and provide the FWHM/resolution plots.  These can be generated on the fly in the docs.  Lots of examples of this in the karllark/dust_extinction package.

**Comment by karllark** [comment]
Also, could you fix the codestyle issues that are causing the tests to fail?  These were introduced in a previous pull request.

**Comment by jdtsmith** [comment]
> Also, could you fix the codestyle issues that are causing the tests to fail? These were introduced in a previous pull request.

I could, but it would be better if someone else did so to exercise the instrument pack functionality.

**Comment by jdtsmith** [comment]
> Also, could you fix the codestyle issues that are causing the tests to fail? These were introduced in a previous pull request.

Are we using a particular automated linter?

**Comment by karllark** [comment]
If you run `black` on the files you update, it will cleanup most of the codestyle issues.  That's what I do so that I don't have to learn and remember all the codestyle rules.

**Comment by karllark** [comment]
We should separate the automated testing issues from getting people to test the code.  They serve different purposes.

**Comment by jdtsmith** [comment]
> We should separate the automated testing issues from getting people to test the code. They serve different purposes.

Violent agreement: for sure we need more hands-on testing, and test spectra under `data/`.  Automated tests can follow.

**Comment by jdtsmith** [comment]
Hey I got a green check!  I also figured out how to run flake8 continuously using the same settings from tox.ini, so hopefully I'll be a net entropy reducer now.  This is ready to merge.  I'm sure we'll need to tweak coefficients as we test against real spectra, but something is better than nothing.  Any objections anyone?

**Review by karllark — APPROVED** [review]
Looks good to me.

**Comment by jdtsmith** [comment]
Thanks.

**Pull request merged**
