### PR TITLE
Fix tox run

### LINKED ISSUE #251: weird test issue
Does anyone familiar with the CI setup here understand this issue?  Seems to be recurring for most of our tests. 

```
py310-cov: failed with pass_env values cannot contain whitespace, use comma to have multiple values in a single line, invalid values found 'HOME WINDIR LC_ALL LC_CTYPE CC CI TRAVIS'
```

### PR DESCRIPTION
**Pull request by drvdputt**
Fixes #251

### CODE REVIEW

**Comment by drvdputt** [comment]
Dev_test is failing. 

```
Run tox -e py310-devdeps
py310-devdeps: install_deps> python -I -m pip install ./:NIGHTLY:numpy git+https://github.com/astropy/astropy.git
ERROR: Invalid requirement: './:NIGHTLY:numpy'
Hint: It looks like a path. File './:NIGHTLY:numpy' does not exist.
py310-devdeps: exit 1 (1.12 seconds) /home/runner/work/pahfit/pahfit> python -I -m pip install ./:NIGHTLY:numpy git+https://github.com/astropy/astropy.git pid=1688
  py310-devdeps: FAIL code 1 (1.40 seconds)
  evaluation failed :( (2.03 seconds)
```

NIGHTLY is defined in tox.ini as 

```
[tox]
indexserver =
    NIGHTLY = https://pypi.anaconda.org/scipy-wheels-nightly/simple
```

But the "indexserver" option was already deprecated since tox version 2.3.1 at least. 
https://tox.wiki/en/2.3.1/config.html

But no completely equivalent alternative has been offered https://github.com/tox-dev/tox/issues/1357.

**Comment by drvdputt** [comment]
@karllark have you run into this issue before?

**Comment by karllark** [comment]
Yes, I have seen this.  I removed the test for dev with the nightly numpy build.  In the end decided this was not needed.

**Comment by drvdputt** [comment]
The only thing that's failing now, is a warning that some things of github actions are deprecated. This is because github will be moving from NodeJS 12 to NodeJS 16 this summer.

https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

Looks like we'll need to update the actions versions, e.g. change  `- uses: actions/checkout@v1` to v3.

**Pull request merged**
