### PR TITLE
Simple FWHM Fix

### PR DESCRIPTION
**Pull request by jdtsmith**
This is a simple fix for the overly generous 2x FWHM (see #174), which led to spurious fits.  This simply hard-codes the 10% for now.  In the near term, we plan to implement a new Instrument Pack/Science Pack with generator, making this code irrelevant.

### CODE REVIEW

**Comment by karllark** [comment]
Also needs the testing parameters update as this changes the results for M101.

**Comment by jdtsmith** [comment]
I'm not as familiar with the test structure; can someone else take a look at that?

**Comment by karllark** [comment]
For now, it might be best to accept failing tests and merge if we have good confidence that it is just needing to update the cached fit values.  There are now multiple PRs that have this test failure.  Then I can do a "quick" PR to fix the failing tests after the different merges are done. 

Or another solution is that I could provide the needed code snippet that would generate the lines that would need to be cut/pasted in to the test function.

Thoughts?

**Comment by jdtsmith** [comment]
If we have a few ongoing changes in this category, perhaps “clean up after” is the right approach. I demoed my own branch at the workshop yesterday so probably good to get some of these in.

**Review by karllark — APPROVED** [review]
A simple fix.  Definitely need to fix this later "properly."

**Comment by karllark** [comment]
Merging now.  Will fix failing tests in a separate PR.

**Pull request merged**
