### PR TITLE
Addition of 4 more ISO-SWS spectra of Orion.

### PR DESCRIPTION
**Pull request by els1**

### CODE REVIEW

**Comment by Ameek-Sidhu** [comment]
Looks good to me. Thank You for uploading Spectra Els!

**Review by Ameek-Sidhu — COMMENTED** [review]
Looks good.

**Review by karllark — APPROVED** [review]
Looks good to me.

**Comment by karllark** [comment]
Ready to merge?  Or one more review needed?

**Comment by els1** [comment]
Ready to merge.

**Pull request merged**
