### PR TITLE
Modification of the PAHFIT v2.1 docs

### PR DESCRIPTION
**Pull request by ThomasSYLai**
This PR is a replacement for PR #138. The text has been edited following the comments. The figure of the fitted results of the 2.5-38 µm spectrum has also been added.

### CODE REVIEW

**Comment by ThomasSYLai** [comment]
@karllark, I didn't quite get where this warning --- "/home/runner/work/pahfit/pahfit/docs/PAHFIT_v2.1.rst:document isn't included in any toctree" is coming from. Can you point me to a correct way to fix this? Thanks!

**Comment by karllark** [comment]
> @karllark, I didn't quite get where this warning --- "/home/runner/work/pahfit/pahfit/docs/PAHFIT_v2.1.rst:document isn't included in any toctree" is coming from. Can you point me to a correct way to fix this? Thanks!

You need to include a link to version_description.rst in index.rst so that users can find the description of the different versions.  Just add it to the list of topics in "User Documentation."

**Comment by ThomasSYLai** [comment]
> > @karllark, I didn't quite get where this warning --- "/home/runner/work/pahfit/pahfit/docs/PAHFIT_v2.1.rst:document isn't included in any toctree" is coming from. Can you point me to a correct way to fix this? Thanks!
> 
> You need to include a link to version_description.rst in index.rst so that users can find the description of the different versions. Just add it to the list of topics in "User Documentation."

Thanks. I've added the links to index.rst.

**Comment by karllark** [comment]
Great.  Will merge this when PR #116 is merged.

**Review by jdtsmith — APPROVED** [review]
This looks good and should be merged along with @ThomasSYLai 's v2.1 PR.

**Pull request merged**
